language: node_js

before_script:
  - TRAVIS_TAG=`date +%Y-%m-%d`
  #  - TRAVIS_TAG=`git tag | grep -v rc | sort -t. -k 1,1n -k 2,2n -k 3,3n -k 4,4n | sed '1!G;h;$!d' | sed -n 1p`
  - uname -a

script:
  - npm install
  - npm run build

before_deploy:
  - echo tolsta $TRAVIS_OS_NAME $BUILD_TYPE $TRAVIS_BRANCH $TRAVIS_TAG

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: public
    keep_history: false
    on:
      repo: sthormio/progression-framework
      branches:
        except:
          - gh-pages